// Generated by CoffeeScript 1.8.0
(function() {
  var escapeXML, escapeXMLCharacter;

  escapeXMLCharacter = function(c) {
    return '&' + {
      '&': 'amp',
      '<': 'lt',
      '>': 'gt',
      "'": 'apos',
      '"': 'quot'
    }[c] + ';';
  };

  escapeXML = function(s) {
    return s.replace(/([&<>'"])/g, escapeXMLCharacter);
  };

  module.exports = {
    VERSION: '0.0.4',
    escapeXML: escapeXML
  };

}).call(this);
